# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parkings.Driver'),
            preserve_default=False,
        ),
    ]
