# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0002_car_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parking',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parking',
            name='number',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
