# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0004_auto_20170117_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='patent',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
